package edu.vanderbilt.mc.biostat.tracker;

import java.awt.Color;

public class Window extends javax.swing.JFrame {

  private App parent;
  private Activity currentActivity;
  private boolean activityNameEntered = false;
  private boolean activityTagsEntered = false;

  /**
   * Creates new form Window
   */
  public Window(App parent) {
    this.parent = parent;
    initComponents();
  }

  private void updateActivityForm() {
    if (!activityNameEntered) {
      txtActivity.setForeground(Color.gray);
      txtActivity.setText("Activity");
    }
    if (!activityTagsEntered) {
      txtTags.setForeground(Color.gray);
      txtTags.setText("Tags");
    }
  }

  private void updateCurrentActivity() {
    if (currentActivity == null) {
      lblCurrentActivity.setText("No activity");
      btnStopTracking.setEnabled(false);
    } else {
      lblCurrentActivity.setText(currentActivity.name);
      btnStopTracking.setEnabled(true);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCurrentActivity = new javax.swing.JPanel();
        btnStopTracking = new javax.swing.JButton();
        lblCurrentActivity = new javax.swing.JLabel();
        lblCurrentTime = new javax.swing.JLabel();
        pnlNewActivity = new javax.swing.JPanel();
        txtActivity = new javax.swing.JTextField();
        txtTags = new javax.swing.JTextField();
        btnStartTracking = new javax.swing.JButton();
        scrlToday = new javax.swing.JScrollPane();
        tblToday = new edu.vanderbilt.mc.biostat.tracker.ActivityTable();
        lblToday = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Time Tracker");

        pnlCurrentActivity.setFont(pnlCurrentActivity.getFont());

        btnStopTracking.setFont(btnStopTracking.getFont());
        btnStopTracking.setText("Stop tracking");
        btnStopTracking.setEnabled(false);
        btnStopTracking.setPreferredSize(new java.awt.Dimension(135, 25));
        btnStopTracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopTrackingActionPerformed(evt);
            }
        });

        lblCurrentActivity.setFont(lblCurrentActivity.getFont().deriveFont(lblCurrentActivity.getFont().getSize()+4f));
        lblCurrentActivity.setText("No activity");

        lblCurrentTime.setFont(lblCurrentTime.getFont());

        javax.swing.GroupLayout pnlCurrentActivityLayout = new javax.swing.GroupLayout(pnlCurrentActivity);
        pnlCurrentActivity.setLayout(pnlCurrentActivityLayout);
        pnlCurrentActivityLayout.setHorizontalGroup(
            pnlCurrentActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCurrentActivityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCurrentActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCurrentActivityLayout.createSequentialGroup()
                        .addComponent(lblCurrentActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStopTracking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCurrentActivityLayout.createSequentialGroup()
                        .addComponent(lblCurrentTime)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCurrentActivityLayout.setVerticalGroup(
            pnlCurrentActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCurrentActivityLayout.createSequentialGroup()
                .addGroup(pnlCurrentActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCurrentActivity)
                    .addComponent(btnStopTracking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCurrentTime)
                .addGap(21, 21, 21))
        );

        pnlNewActivity.setFont(pnlNewActivity.getFont());

        txtActivity.setFont(txtActivity.getFont().deriveFont(txtActivity.getFont().getSize()+3f));
        txtActivity.setForeground(java.awt.Color.gray);
        txtActivity.setText("Activity");
        txtActivity.setPreferredSize(new java.awt.Dimension(150, 25));
        txtActivity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtActivityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtActivityFocusLost(evt);
            }
        });

        txtTags.setFont(txtTags.getFont().deriveFont(txtTags.getFont().getSize()+3f));
        txtTags.setForeground(java.awt.Color.gray);
        txtTags.setText("Tags");
        txtTags.setPreferredSize(new java.awt.Dimension(150, 25));
        txtTags.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTagsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTagsFocusLost(evt);
            }
        });

        btnStartTracking.setFont(btnStartTracking.getFont());
        btnStartTracking.setText("Start tracking");
        btnStartTracking.setPreferredSize(new java.awt.Dimension(135, 25));
        btnStartTracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartTrackingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNewActivityLayout = new javax.swing.GroupLayout(pnlNewActivity);
        pnlNewActivity.setLayout(pnlNewActivityLayout);
        pnlNewActivityLayout.setHorizontalGroup(
            pnlNewActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewActivityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtActivity, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTags, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnStartTracking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlNewActivityLayout.setVerticalGroup(
            pnlNewActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewActivityLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlNewActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTags, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStartTracking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        scrlToday.setBackground(new java.awt.Color(255, 255, 255));
        scrlToday.setFont(scrlToday.getFont());

        tblToday.setModel(new ActivityTableModel());
        tblToday.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblToday.setDoubleBuffered(true);
        tblToday.setEditable(false);
        tblToday.setShowHorizontalLines(false);
        tblToday.setShowVerticalLines(false);
        tblToday.setSortable(false);
        tblToday.setTableHeader(null);
        scrlToday.setViewportView(tblToday);

        lblToday.setFont(lblToday.getFont().deriveFont(lblToday.getFont().getStyle() | java.awt.Font.BOLD));
        lblToday.setText("Today");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNewActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCurrentActivity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrlToday)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblToday)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCurrentActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlNewActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblToday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrlToday, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );

        System.out.println(lblToday.getUI().getClass().getName());

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void txtActivityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtActivityFocusGained
    if (!activityNameEntered) {
      txtActivity.setForeground(Color.black);
      txtActivity.setText("");
    }
  }//GEN-LAST:event_txtActivityFocusGained

  private void txtActivityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtActivityFocusLost
    activityNameEntered = !txtActivity.getText().isEmpty();
    updateActivityForm();
  }//GEN-LAST:event_txtActivityFocusLost

  private void txtTagsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTagsFocusGained
    if (!activityTagsEntered) {
      txtTags.setForeground(Color.black);
      txtTags.setText("");
    }
  }//GEN-LAST:event_txtTagsFocusGained

  private void txtTagsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTagsFocusLost
    activityTagsEntered = !txtTags.getText().isEmpty();
    updateActivityForm();
  }//GEN-LAST:event_txtTagsFocusLost

  private void btnStartTrackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartTrackingActionPerformed
    if (!activityNameEntered) {
      return;
    }

    String tagNames = activityTagsEntered ? txtTags.getText() : null;
    Activity activity = parent.startActivity(txtActivity.getText(), tagNames);
    if (activity != null) {
      if (currentActivity != null) {
        parent.stopActivity(currentActivity);
      }
      currentActivity = activity;
      updateCurrentActivity();

      activityNameEntered = activityTagsEntered = false;
      updateActivityForm();

      ((ActivityTableModel) tblToday.getModel()).updateActivities();
    }
  }//GEN-LAST:event_btnStartTrackingActionPerformed

  private void btnStopTrackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopTrackingActionPerformed
    parent.stopActivity(currentActivity);
    currentActivity = null;
    updateCurrentActivity();

    ((ActivityTableModel) tblToday.getModel()).updateActivities();
  }//GEN-LAST:event_btnStopTrackingActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartTracking;
    private javax.swing.JButton btnStopTracking;
    private javax.swing.JLabel lblCurrentActivity;
    private javax.swing.JLabel lblCurrentTime;
    private javax.swing.JLabel lblToday;
    private javax.swing.JPanel pnlCurrentActivity;
    private javax.swing.JPanel pnlNewActivity;
    private javax.swing.JScrollPane scrlToday;
    private edu.vanderbilt.mc.biostat.tracker.ActivityTable tblToday;
    private javax.swing.JTextField txtActivity;
    private javax.swing.JTextField txtTags;
    // End of variables declaration//GEN-END:variables
}
