/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.vanderbilt.mc.biostat.tracker;

/**
 *
 * @author stephej1
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCurrentActivity = new javax.swing.JPanel();
        btnStopTracking = new javax.swing.JButton();
        lblCurrentActivity = new javax.swing.JLabel();
        lblCurrentTime = new javax.swing.JLabel();
        pnlNewActivity = new javax.swing.JPanel();
        txtActivity = new javax.swing.JTextField();
        txtTags = new javax.swing.JTextField();
        btnStartTracking = new javax.swing.JButton();
        scrlToday = new javax.swing.JScrollPane();
        lstToday = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Time Tracker");
        setPreferredSize(new java.awt.Dimension(500, 300));

        btnStopTracking.setText("Stop tracking");
        btnStopTracking.setEnabled(false);
        btnStopTracking.setPreferredSize(new java.awt.Dimension(135, 25));

        lblCurrentActivity.setFont(lblCurrentActivity.getFont().deriveFont(lblCurrentActivity.getFont().getSize()+6f));
        lblCurrentActivity.setText("No activity");

        javax.swing.GroupLayout pnlCurrentActivityLayout = new javax.swing.GroupLayout(pnlCurrentActivity);
        pnlCurrentActivity.setLayout(pnlCurrentActivityLayout);
        pnlCurrentActivityLayout.setHorizontalGroup(
            pnlCurrentActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCurrentActivityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCurrentActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCurrentActivityLayout.createSequentialGroup()
                        .addComponent(lblCurrentActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStopTracking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCurrentActivityLayout.createSequentialGroup()
                        .addComponent(lblCurrentTime)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCurrentActivityLayout.setVerticalGroup(
            pnlCurrentActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCurrentActivityLayout.createSequentialGroup()
                .addGroup(pnlCurrentActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCurrentActivity)
                    .addComponent(btnStopTracking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCurrentTime)
                .addGap(21, 21, 21))
        );

        txtActivity.setFont(txtActivity.getFont().deriveFont(txtActivity.getFont().getSize()+4f));
        txtActivity.setText("Activity");
        txtActivity.setPreferredSize(new java.awt.Dimension(150, 25));

        txtTags.setFont(txtTags.getFont().deriveFont(txtTags.getFont().getSize()+4f));
        txtTags.setText("Tags");
        txtTags.setPreferredSize(new java.awt.Dimension(150, 25));

        btnStartTracking.setText("Start tracking");
        btnStartTracking.setPreferredSize(new java.awt.Dimension(135, 25));

        javax.swing.GroupLayout pnlNewActivityLayout = new javax.swing.GroupLayout(pnlNewActivity);
        pnlNewActivity.setLayout(pnlNewActivityLayout);
        pnlNewActivityLayout.setHorizontalGroup(
            pnlNewActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewActivityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtActivity, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTags, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnStartTracking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlNewActivityLayout.setVerticalGroup(
            pnlNewActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewActivityLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlNewActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTags, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStartTracking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        scrlToday.setBackground(new java.awt.Color(255, 255, 255));

        lstToday.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrlToday.setViewportView(lstToday);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNewActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCurrentActivity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrlToday)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCurrentActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlNewActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlToday, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Window().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartTracking;
    private javax.swing.JButton btnStopTracking;
    private javax.swing.JLabel lblCurrentActivity;
    private javax.swing.JLabel lblCurrentTime;
    private javax.swing.JList lstToday;
    private javax.swing.JPanel pnlCurrentActivity;
    private javax.swing.JPanel pnlNewActivity;
    private javax.swing.JScrollPane scrlToday;
    private javax.swing.JTextField txtActivity;
    private javax.swing.JTextField txtTags;
    // End of variables declaration//GEN-END:variables
}
